---
- name: upgrade
  apt:
    upgrade: full
    force: yes
    update_cache: yes
    cache_valid_time: 86400
  sudo: yes
  when: ansible_os_family == 'Debian'

- name: install apt-transport-https
  apt: name=apt-transport-https state=present update_cache=yes
  sudo: yes
  when: ansible_os_family == 'Debian'